### ISSUE TITLE
Review existing modules that might be helpful

### ISSUE THREAD

**Issue by ymdahi** [learnfullabs/h5p-xapi#3]
H5P module
- https://www.drupal.org/project/h5p

H5P Analytics:
- https://www.drupal.org/project/h5p_analytics
- Similar goal of module, but this module sends xAPI data to an external service (Learning Record Store (LRS)) instead of saving it locally. 

Opigno Tincan API:
- https://www.drupal.org/project/opigno_tincan_api
- Similar to h5p analytics, but provides xAPI for other things, such as node views.

**Comment by danrod96** [comment]
We can close this issue, since the module h5p-xapi has already the implementation for saving the xapi json into the DB:

https://github.com/learnfullabs/h5p-xapi/blob/main/src/Plugin/rest/resource/H5PXAPISaveEventsUser.php

TODO:

- Parse the JSON data and store it in a different table
- Save the data in a MongoDB DB ?
